import 'models/question_model.dart';

final List<QuizQuestion> quizQuestions = [
  QuizQuestion(question: 'The capital of France is Paris.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The Sun revolves around the Earth.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'Water boils at 100°C at sea level.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'Mount Everest is the tallest mountain in the world.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'Sharks are mammals.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The Great Wall of China is visible from space.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'Lightning never strikes the same place twice.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'Humans have walked on Mars.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The chemical symbol for gold is Au.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The Pacific Ocean is the largest ocean on Earth.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'Bats are blind.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The human body has four lungs.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The Mona Lisa was painted by Leonardo da Vinci.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The currency of Japan is the Yen.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The Earth has two moons.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'Sound travels faster than light.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The square root of 64 is 8.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The Amazon River is the longest river in the world.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'Penguins can fly.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The human heart has four chambers.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The Statue of Liberty was a gift from France.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'Albert Einstein developed the theory of relativity.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The capital of Australia is Sydney.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'Venus is the closest planet to the Sun.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The Eiffel Tower is located in Berlin.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'A group of lions is called a pride.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The human skeleton is made up of over 200 bones.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The moon produces its own light.', answer: AnswerOption.falseOption),
  QuizQuestion(question: 'The chemical formula for water is H2O.', answer: AnswerOption.trueOption),
  QuizQuestion(question: 'The Titanic sank in 1912.', answer: AnswerOption.trueOption),
];